site_name: "{{ values.name }} Documentation"
site_description: "Documentação técnica para o serviço ${{ values.name }}"
site_author: "Equipe Backstage"

docs_dir: docs

nav:
  - Home: index.md
  - Guia de Uso:
      - Instalação: guia/instalacao.md
  - Referência:
      - Configurações: referencia/configuracoes.md

plugins:
  - search
  - techdocs-core

theme:
  name: material
  palette:
    primary: "indigo"
    accent: "indigo"
  font:
    text: Roboto
    code: Roboto Mono

extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js

techdocs:
  site_name: "{{ values.name }} TechDocs"